services:
  server:
    build: ./server
    container_name: pocostories_server_c
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - DB_NAME=pocostories
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    container_name: pocostories_client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    # stdin_open: true
    # tty: true

  db:
    image: postgres
    container_name: db_c
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocostories
      POSTGRES_USER: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./server/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d pocostories -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_c
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - ./pgadmin:/var/lib/pgadmin