services:
  server:
    build: ./server
    container_name: pocostories_server_c
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - DB_NAME=pocostories
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    container_name: pocostories_client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules

  db:
    image: postgres
    container_name: pocostories_db_c
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocostories
      POSTGRES_USER: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./server/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d pocostories -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
