services:
  server:
    build: ./server
    container_name: pocostories_server_c
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=4000
  client:
    build: ./client
    container_name: pocostories_client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true